// LOCALHOST
### Get all students
GET http://localhost:8080/students


### Get student by id
GET http://localhost:8080/students/65d191ae58472b01d16cf504


### Create student
POST http://localhost:8080/students HTTP/1.1
content-type: application/json

{
    "name": "Jose",
    "lastName": "Luis",
    "email": "jose@gmail.com",
    "phone": "21156415",
    "course": "biology"
}

### PUT student
PUT http://localhost:8080/students/65d191ae58472b01d16cf504 HTTP/1.1
content-type: application/json

{
    "name": "Jose edited",
    "lastName": "Luis",
    "email": "jose@gmail.com",
    "phone": "21156415",
    "course": "biology and edited"
}


### DELETE student
DELETE http://localhost:8080/students/65d191ae58472b01d16cf504 HTTP/1.1



// PRODUCTION Deploy
### Get all students
GET https://school-api-test.onrender.com/students


### Get student by id
GET https://school-api-test.onrender.com/students/65d191c858472b01d16cf505


### Create student
POST https://school-api-test.onrender.com/students HTTP/1.1
content-type: application/json

{
    "name": "Jose new",
    "lastName": "Luis",
    "email": "jose@gmail.com",
    "phone": "21156415",
    "course": "biology"
}


### PUT student
PUT https://school-api-test.onrender.com/students/65d191c858472b01d16cf505 HTTP/1.1
content-type: application/json

{
    "name": "Jose edited",
    "lastName": "Luis",
    "email": "jose@gmail.com",
    "phone": "21156415",
    "course": "biology and edited"
}


### DELETE student
DELETE https://school-api-test.onrender.com/students/65d191c858472b01d16cf505 HTTP/1.1